name: build

on: [workflow_dispatch]

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        sm_version:
          - "1.11"

        mm_version:
          - "1.12"

        include:
          - mm_version: "1.12"
            mm_branch: "master"

          - sm_version: "1.11"
            sm_branch: "master"

          - os: ubuntu-latest
            os_short: linux
            target-archs: x86,x86_64

          - os: windows-latest
            os_short: win
            target-archs: x86,x86_64
            
          - os: macos-latest
            os_short: macos
            target-archs: x86_64

    steps:
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -yq --no-install-recommends g++-multilib

      - name: Checking out SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive

      - name: Checking out MM:Source
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.mm_branch }}
          path: metamod-${{ matrix.mm_version }}

      - name: Checking out AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild
      
      - name: Setting up ambuild
        working-directory: ambuild
        run: python setup.py install
        
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checking out own repository
        uses: actions/checkout@v2
        with:
          path: extension

      - name: Compiling sm-ripext files
        working-directory: extension
        shell: bash
        run: |
          mkdir build
          cd build
          perl ../curl/lib/mk-ca-bundle.pl
          python ../configure.py --enable-optimize --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}" --mms-path="${{ github.workspace }}/metamod-${{ matrix.mm_version }} --targets=${{ matrix.target-archs }}"
          ambuild
      - name: Uploading package
        uses: actions/upload-artifact@v2
        with:
          name: sm-ripext-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: extension/build/package
